-- Seed baseline categories
INSERT INTO categories (id, name, slug)
VALUES
  (gen_random_uuid(), 'Sneakers', 'sneakers'),
  (gen_random_uuid(), 'Boots', 'boots'),
  (gen_random_uuid(), 'Sandals', 'sandals')
ON CONFLICT (slug) DO NOTHING;

-- Seed baseline products
INSERT INTO products (
  id,
  name,
  brand,
  description,
  price,
  original_price,
  images,
  gender,
  shoe_type,
  sizes,
  colors,
  material,
  stock_quantity,
  rating,
  review_count,
  sales_count,
  featured,
  care_instructions,
  status,
  category_id
)
SELECT
  gen_random_uuid(),
  product.name,
  product.brand,
  product.description,
  product.price,
  product.original_price,
  product.images,
  product.gender,
  product.shoe_type,
  product.sizes,
  product.colors,
  product.material,
  product.stock_quantity,
  product.rating,
  product.review_count,
  product.sales_count,
  product.featured,
  product.care_instructions,
  product.status,
  (SELECT id FROM categories WHERE slug = product.category_slug LIMIT 1)
FROM (
  VALUES
    (
      'Air Nova Runner',
      'Nova',
      'Lightweight daily trainer built for comfort.',
      17998.5,
      22498.5,
      ARRAY['https://images.unsplash.com/photo-1542291026-7eec264c27ff'],
      'unisex',
      'sneakers',
      ARRAY['7','8','9','10','11'],
      ARRAY['black','white'],
      'mesh',
      24,
      4.6,
      128,
      52,
      true,
      'Spot clean only.',
      'active',
      'sneakers'
    ),
    (
      'Trail Crest Boot',
      'Summit',
      'All-weather boot with rugged grip.',
      28498.5,
      32998.5,
      ARRAY['https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77'],
      'men',
      'boots',
      ARRAY['8','9','10','11','12'],
      ARRAY['brown'],
      'leather',
      12,
      4.8,
      87,
      31,
      false,
      'Condition leather monthly.',
      'active',
      'boots'
    ),
    (
      'Coastline Slide',
      'Maris',
      'Easy slip-on sandal for warm days.',
      7498.5,
      8998.5,
      ARRAY['https://images.unsplash.com/photo-1514989940723-e8e51635b782'],
      'women',
      'sandals',
      ARRAY['6','7','8','9','10'],
      ARRAY['tan'],
      'synthetic',
      40,
      4.3,
      64,
      18,
      true,
      'Rinse with fresh water.',
      'active',
      'sandals'
    )
) AS product(
  name,
  brand,
  description,
  price,
  original_price,
  images,
  gender,
  shoe_type,
  sizes,
  colors,
  material,
  stock_quantity,
  rating,
  review_count,
  sales_count,
  featured,
  care_instructions,
  status,
  category_slug
)
ON CONFLICT DO NOTHING;
